### ISSUE TITLE
Updated background shadows for monsters.

### ISSUE THREAD

**Issue by AndrXi** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#11]
I've completed adding the background shadows to all monsters in the 1st tiles.png.
I'll see if I can get the others done if there's any missing.

I'll need to upload the modified tile_config.json somewhere.
I think I was thorough but it may need to be revised.

**Comment by SomeDeadGuy** [comment]
Kewl. You can hit me up on discord @SomeDeadGuy#3894 we will discuss it there.
Or make a pull request, but i have no idea how! ;)
