### ISSUE TITLE
Lost 

### ISSUE THREAD

**Issue by Pupsi-Mupsi** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#15]
Hi there,

some previously merged shadows and such were lost after your last commit.

Those changes seem to be gone now:
https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset/pull/14/files

Take look at the screenshot below...

Happy Holidays!

Left till commit 339 - right after 339
![grafik](https://user-images.githubusercontent.com/44737997/50423343-4508f200-0854-11e9-8fd5-271cdf0726da.png)

**Comment by SomeDeadGuy** [comment]
I will look at you pull request and will add them by hand in next update.
But not all of them! Some tiny creatures should not have shadows this big (i will create tiny shadows for those), it is bigger then themselfs! :D
Also fish should not have shadows at all, cause it is lives in water.

**Comment by Pupsi-Mupsi** [comment]
All set! Thank you.
