### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by DeltaKris** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#17]
I always have the habit of when you launch an update for your tileset, I update, always... but now I came across a possible bug, my hair is duplicated and I can not put neither hair or skin, is this a bug?

My English is not good, but I hope you could understand.

![screenshot_1](https://user-images.githubusercontent.com/45604592/52388417-68d76e80-2a75-11e9-84fd-33e047abfd58.png)

**Comment by SomeDeadGuy** [comment]
What mods are you using?
It looks to me you using some sort of hair mod. What is it?
Hair skin and eyes are gonna be in vanilla game soon, maybe it has something to do with it.

**Comment by DeltaKris** [comment]
It is as if he already had his own hair without putting anything.
Before upgrading your tileset, I upgraded C:DDA to the new version
I tested it, and everything was fine.
But I updated you tileset and stayed this way..
The tileset only worked without problem if I did not manually updated, In case, if I did not get downloaded on github.

**Comment by DeltaKris** [comment]
I'm using the compatible mods with your tileset, the hair and the tattoo with hibrid items.

**Comment by SomeDeadGuy** [comment]
You using mods linked on this git, right? Those what are on google disk?
I need to recreate this situation myself and see what i will get.
...
I got it! This is my mistake. In tileset folder there is tileset.txt file.
Update the game again. Then put all files from this tileset, but do not put tileset.txt inside. It has wrong information in it.

**Comment by SomeDeadGuy** [comment]
Gonna be fixed in next update latter today.

**Comment by DeltaKris** [comment]
Okay, thanks bro, you saved my life.
