### ISSUE TITLE
Hidden Tree Trunks 

### ISSUE THREAD

**Issue by DaAngus** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#23]
I have run into this issue the second Time now, so I thought why not post it:
Some Tree Trunks are invisible but only with MSX++Live_People
![Screenshot from 2019-03-12 13-54-02](https://user-images.githubusercontent.com/45876504/54202056-18658d80-44c7-11e9-9602-0cc2a0e6a349.png)
Got a save game attached, its the second world where it happened, over different versions.
[15x.zip](https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset/files/2956921/15x.zip)

**Comment by SomeDeadGuy** [comment]
Something to do with random sprites. Gonna fix that very soon

**Comment by SomeDeadGuy** [comment]
fixed
