### ISSUE TITLE
Why character customisation doesn't works

### ISSUE THREAD

**Issue by Adevald** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#24]
Привет, а что там с кастомизацией персонажа? Почему она не пашет? Там просто люди в группе жалуются что нету у дверей тайлов, вот я и думал обновить тайлсет, а у тебя тут проблема какая-то?

https://pp.userapi.com/c845218/v845218475/1d7797/j5ZKxRBy5ZI.jpg

**Comment by SomeDeadGuy** [comment]
Ты самую последнюю эксперименталку используешь?

**Comment by Adevald** [comment]
@SomeDeadGuy  Евстевстственнно

а ты случаем в не тот дед из /vg/?

**Comment by SomeDeadGuy** [comment]
Кто же я ещё?
Тогда у тебя косяк какой-то. У меня на последней эксперименталке при создании персонажа в трейтах можно внешку менять и она показывается на персонаже. Случайные нпс тоже с рандомным луком спавнятся.

**Comment by Adevald** [comment]
@SomeDeadGuy У тебя у самого же подписано (no character customization), т.е. это особо ничего не значит и можно въёбывать на последнюю версию в сборку?

Ебать я подписался мод делать который Фонд добавил бы в игру.

**Comment by SomeDeadGuy** [comment]
Да не, "но карахтер кастомиз" это для стабилки 0.D, там ещё не завезли кастомизацию, поэтому персонажа я там не лысым сделал.
Тебе нужна папка gfx, которая рядом лежит, там последняя версия.

**Comment by SomeDeadGuy** [comment]
Вообще я бы всю эту болтовню в кудахт перенёс, напиши мне там, я тебе смогу чаще отвечать. Это закрываю, ибо не иссюй.
