### ISSUE TITLE
Mainlined appearance?

### ISSUE THREAD

**Issue by GearheadLydia** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#25]
It looks like skin tone, hair, and facial hair have all been mainlined fairly recently. [\(Link to the new mutation_appearance.json.\)](https://github.com/nexusmrsep/Cataclysm-DDA/blob/master/data/json/mutation_appearance.json) While unfortunately the new version of the appearance doesn't have colors for the facial hair, it might be a good idea to add support for this.

**Comment by SomeDeadGuy** [comment]
so friggin tired of this...
IT IS ALREADY **!!!IN THE TILESET!!!**
41f12aa2d03b61eac7fa58571ced3da5208d45ab
