### ISSUE TITLE
New floor texture makes it hard to see items

### ISSUE THREAD

**Issue by GearheadLydia** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#26]
The new herringbone wood texture for default floors looks great, but it's a little high-contrast and it makes it hard to see items against it. It's noticeable enough that I'd splice in a replacement of my own every time I updated the tileset, but I may not be the only one having this issue; and the tile is used repeatedly enough that doing it as a tileset mod seems close to impossible to do reliably.

Sorry if this is super picky. I wouldn't bring it up if it wasn't both actively distracting and apparently hard to fix (and keep fixed).

**Comment by SomeDeadGuy** [comment]
I like this floor texture, it will stay for now, sorry.
BUT, i can make a mod what will bring back old floor texture back.

**Comment by SomeDeadGuy** [comment]
Mod added.
