### ISSUE TITLE
All NPCs look really angry

### ISSUE THREAD

**Issue by Kitaragna** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#27]
It looks like a recent change made a slight tweak to character eyes - a single changed pixel has changed everyone's eyes from open and wide to pissed off. Is this intentional? It doesn't really seem to fit with the rest of the aesthetics

**Comment by SomeDeadGuy** [comment]
😠

**Comment by SomeDeadGuy** [comment]
Ha ha, i know. It is something i am experimenting with. I want to bring character mood on character face somehow.
Just trying some different things to see what can be done with this.
I am gonna revert them back to normal in next update later today. Dont worry. :)

**Comment by Kitaragna** [comment]
Ah, definitely a great idea! I noticed a while ago my character's eyes would look glossy when holding an item. Thanks for the heads up.

**Comment by SomeDeadGuy** [comment]
Fixed Evil Look :)
