### ISSUE TITLE
Faux fur trenchcoat Deadpeople tile inconsistency

### ISSUE THREAD

**Issue by RarkGrames** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#28]
Describe the bug
Faux fur trenchcoat and sleeveless faux fur trenchcoat tiles are inconsistent to the rest

Expected behavior
Faux fur trenchcoat and sleeveless faux fur trenchcoat should use the duster counterpart tiles, just like the rest of the trenchcoats.

Screenshots
![57554332-743a7e80-7371-11e9-93e7-94ce21cf94d3](https://user-images.githubusercontent.com/50421549/57566590-af1ecf80-73ce-11e9-9db7-dc326a34b7b8.png)

Versions and configuration(please complete the following information):

    OS: Win x64
    Game Version: 0.D-2773-g2d05871 (tiles)
    Graphics version: Tiles
    Mods loaded: Default

**Comment by SomeDeadGuy** [comment]
Trenchcoats separated from dusters.
![trenches](https://user-images.githubusercontent.com/37592026/57714720-c8997300-767d-11e9-969f-7f4f284535e6.png)

**Comment by RarkGrames** [comment]
You're the best.
