### ISSUE TITLE
Off-road wide wheels use the motorbike wheel tile

### ISSUE THREAD

**Issue by RarkGrames** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#29]
Off-road wide wheels (the ones on 4x4 Cars and Tractors) use the tile for motorbike wheel. I think that was because their id was the same or similar, but that has been changed a while ago.

**Comment by SomeDeadGuy** [comment]
Wide wheels were changed. Check them and close this issue if you are happy with them.

**Comment by RarkGrames** [comment]
It is very nice, but I think there is some kind of misunderstanding here. It is different from the motorbike wheel, but it looks like a motorbike off-road wheel. I think it should look like the 24" wide wheel. Are we talking about the same thing?

**Comment by SomeDeadGuy** [comment]
The point is - i have no idea how what [24" wide] even mean! 😄 
I think i need some visual images to get it.

**Comment by RarkGrames** [comment]
:smile: 
(24 inch – around 60 cm).
24" wide wheel is the wheel you can get from trucks (left).
24" off-road wide wheel is the same, just off-road, from tractors (right).
![Névtelen](https://user-images.githubusercontent.com/50421549/58436173-4c168380-80c4-11e9-9121-4e46cb0d372f.png)
They should look like the same, or something. Tractors look really funny with this wheel (this is with the update two hours ago where you changed them a little bit wider, but only on the vehicles).

**Comment by SomeDeadGuy** [comment]
Check it again! I hope i get it this time! 😃

**Comment by RarkGrames** [comment]
I updated UnDeadPeople and it is the same as yesterday. Sorry to bother you with all this. :(

**Comment by SomeDeadGuy** [comment]
post me a screen shot 
i am sure i changed 24" wide wheels to fat version

**Comment by RarkGrames** [comment]
It's strange. Now it has the fat version. I even checked out the new tiles that has been added. Anyways, thanks for your time. :+1:
