### ISSUE TITLE
some mutation problem

### ISSUE THREAD

**Issue by Trokinos** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#3]
Hello,

As those error message do not happen if i use another tileset using the same base (like the MshockXottoplus by example) , i think the problem may be in this tileset then :

18:45:37.359 SDL : src/cata_tiles.cpp:675: tile !overlay_female_mutation_VISCOUS has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_male_mutation_AMORPHOUS has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_male_mutation_QUILLS has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_male_mutation_CHITIN_FUR3 has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_male_mutation_BIRD_EYE has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_female_mutation_QUILLS has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_female_mutation_CHITIN_FUR3 has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_female_mutation_BIRD_EYE has no (valid) foreground nor background
18:45:37.359 SDL : src/cata_tiles.cpp:675: tile overlay_female_mutation_AMORPHOUS has no (valid) foreground nor background
18:45:37.391 SDL : src/cata_tiles.cpp:675: tile overlay_female_mutation_SUNBURN has no (valid) foreground nor background
18:45:37.391 INFO : Loaded tileset: MSX++DEAD_PEOPLE

I play a lot with this tileset (that i like for its variety) but i don't play with mutations so i have not observed if ingame those error lead into actual problems.
But better report it in case you may not have noticed.

**Comment by SomeDeadGuy** [comment]
Yep, them are my mutation errors.
I will get to them soon.

**Comment by SomeDeadGuy** [comment]
Fixed!
