### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by matt32106** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#30]
1/ Which files do you install and where? This is not clear from the read me.

2/ I installed cataclysm via snap and it seems to be version 0.C, is this compatible? (could also be mentioned in the readme?!)

Thanks!

**Comment by SomeDeadGuy** [comment]
1 You take folder called "gfx" and put it where your cataclysm.exe (and main gfx folder) is located. In game menu graphical settings you choose Undead People tileset.

2 i have no idea what snap is  🤔 
but firstmost my tileset is for latest experimental version of the game. 0.D something-something
they located here http://dev.narc.ro/cataclysm/jenkins-latest/

**Comment by matt32106** [comment]
Ok thanks.

FYI snap is a package manager for linux. Somebody made a package for cataclysm.

**Comment by SomeDeadGuy** [comment]
Yeah, it should be compatible. Tileset just adds content mostly. So all stuff from 0.C should be covered.

**Comment by SomeDeadGuy** [comment]
http://dev.narc.ro/cataclysm/jenkins-latest/Linux_x64/Tiles/
Here is latest 0.D experimental releases for Linux btw.
They do not work for you?
