### ISSUE TITLE
Revenant's tile is off centered.

### ISSUE THREAD

**Issue by AluminumAlman** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#31]
While using PKs Rebalancing mod, the revenant's tile is offset to the right by 1 whole tile. This is how it looks in game:
![image](https://user-images.githubusercontent.com/34545746/60399376-3fc29200-9b6c-11e9-8063-799770732ca2.png)
![image](https://user-images.githubusercontent.com/34545746/60399382-4b15bd80-9b6c-11e9-9c1c-5395b1a3e82d.png)
(Yes, the Revenant is inside the Archvile due to this graphical bug)

**Comment by SomeDeadGuy** [comment]
>Revenant is inside the Archvile
![1561772256019](https://user-images.githubusercontent.com/37592026/60399809-3f79c500-9b73-11e9-8b1f-a7bc50fbfd2f.png)

**Comment by SomeDeadGuy** [comment]
Fixed!
