### ISSUE TITLE
Battlemaid tiles need to fix.

### ISSUE THREAD

**Issue by Ezsk** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#32]
"maid_dress_french" and "survivor_maid_dress_french" who added by Battlemaid mod is need to fix.
Those clothes look naked because there is no  "overlay_worn" codes.

Now
`"id": ["overlay_worn_survivor_maid_dress", "maid_dress_french", "overlay_worn_jokyu_fuku"], 
 "fg": 698, "rotates": false `

I Suggest to like this
`"id": ["overlay_worn_survivor_maid_dress", "overlay_worn_maid_dress_french", "overlay_worn_survivor_maid_dress_french", "overlay_worn_jokyu_fuku"], "fg": 698, "rotates": false `

**Comment by SomeDeadGuy** [comment]
fixed
see if it works
