### ISSUE TITLE
Butcher knife doesn't have wielded icon

### ISSUE THREAD

**Issue by Jasorn** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#33]
Currently it appears as a giant knife covering the player, using the same icon as if it was on the floor, instead of being held in hand
![image](https://user-images.githubusercontent.com/5076069/61974528-5eba1580-afac-11e9-8d40-9d3584533a2d.png)

**Comment by SomeDeadGuy** [comment]
Maybe... IT IS GIANT! 0-0

**Comment by Jasorn** [comment]
yeah its like wielding a breaker blade lol

**Comment by SomeDeadGuy** [comment]
Fixed
