### ISSUE TITLE
Steerable wheel graphics no longer work properly

### ISSUE THREAD

**Issue by Kitaragna** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#38]
I guess a recent change to the game added wheel assembly hubs which take some focus away from wheels. One big tweak to this is that wheels are no longer steerable, but rather assembly hubs are. existing vehicles will still have wheels with the (steering) tag attached, but trying to replicate it won't produce the same effect.

Basically, this is unfortunately messing with the graphics of mostly scooters and motorcycles, since their unique appearance is based off of a wheel being steerable, and not the assembly hub.

**Comment by SomeDeadGuy** [comment]
yep, this is the game problem, not a problem of this tileset tho
create issue on cataclysm git please. I will close this one.
