### ISSUE TITLE
Missing tile for “primitive floor”

### ISSUE THREAD

**Issue by BoredEngineer** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#4]
When building “log & sod roof” resulting floor tile is a dot on Black background.

**Comment by SomeDeadGuy** [comment]
![primitive_floor](https://user-images.githubusercontent.com/37592026/48005490-a6e68e80-e124-11e8-87f6-d30e7bf51586.jpg)
Nope, primitive floor working as intended in my game. I did build "log & sod roof", and this what was made.
Are you sure you using my tileset? :)

**Comment by BoredEngineer** [comment]
Not sure anymore :D
I’ll double check...

**Comment by BoredEngineer** [comment]
My apologies, I was using different tileset...
