### ISSUE TITLE
Android Ram

### ISSUE THREAD

**Issue by IcyBloodKatana** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#8]
New to this git stuff so just putting it here.

I play on a low ram android device and am unable to use this pack thanks to how large in size it is sadly. I was hoping you could make a low ram version of this tileset...
Like say the 32x32 just gets resized to 16x16.
I really like this tileset and would love to use it even if the pixels lower, pretty sure there are other players with low ram out there that would love to use this too.

Just a request... or issue depending on how you look at it.
Either way great work setting up this tileset.

**Comment by IcyBloodKatana** [comment]
okay just figured asking was worth a try.
hopefully someone will take up the banner of war against RAM.

**Comment by SomeDeadGuy** [comment]
I guess i will close it. I am no making this tileset for android. I hope the great Android Gods will forgive me. :)
