### ISSUE TITLE
"Missing" Tile - Travois

### ISSUE THREAD

**Issue by AndrXi** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#9]
The Travois currently has the Seat tile and I couldn't find a travois tile in the tileset.
I don't know if it's the intended tile for it , but I'd rather make sure it's known to the creator.

(Also , I would like to thank you for the continued work on the tileset and amazing work you've done thus far , I'd like to let you know your devotion is very appreciated.)

**Comment by SomeDeadGuy** [comment]
It is intended. Not by me tho. It was like this when i started working on Xotto tileset, i think. I have no idea what travois even is! Well, now i know, lol. I will look in to it and see if it can be changed to something what make sence for travois.
(And thank you for support!)

**Comment by AndrXi** [comment]
Thanks for making time for this silly issue.

**Comment by SomeDeadGuy** [comment]
The Travois is IN! Check it out!

**Comment by AndrXi** [comment]
I will!
I'll be closing this.
